services:
 web:
  image: nginx:latest
  container_name: nginx
  restart: always
  ports:
   - "80:80"
  volumes:
   - ./www:/www
   - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
  - php
  - db
 php:
  build:
    context: ./
    dockerfile: Dockerfile
  image: php:8.2-fpm
  container_name: php-fpm
  volumes:
  - ./www:/www
 db:
  image: mysql:latest
  container_name: mysql
  ports:
  - "3306:3306"
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: teste